var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__cb11b5eb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_65e60196._.js")
R.c("server/chunks/ssr/node_modules_next_dist_08570d7f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__76bb8d40._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_75761787.js")
R.m(37823)
module.exports=R.m(37823).exports
